dist: trusty
branches:
  only:
    - develop
    - master
    - kodi-release
language: python
python:
  - "2.6"
  - "2.7"
  - "3.6"
before_install:
  - export PYTHONIOENCODING=UTF-8

install:
  - pip install codecov codacy-coverage mock future
  - pip install https://github.com/romanvm/script.module.simpleplugin/archive/develop.zip
script:
  - coverage run tests.py
after_success:
  - codecov
  - coverage xml
  - python-codacy-coverage -r coverage.xml
