dist: trusty
language: python
python:
  - "2.6"
  - "2.7"
  - "3.6"
env:
  global:
    - ADDON_ID=weather.gismeteo
    - BRANCH=krypton
    - PYTHONIOENCODING=UTF-8
install:
  - pip install -q -r requirements.txt
script:
  - coverage run tests.py
after_success:
  - codecov
  - coverage xml -o cobertura.xml
  - bash <(curl -Ls https://coverage.codacy.com/get.sh)
before_deploy:
  - pip install -q git+https://github.com/romanvm/kodi-addon-submitter.git
  - submit-addon -s -z -m $ADDON_ID
deploy:
  # Publish an installable ZIP to GitHub Releases
  - provider: releases
    api_key: $GH_TOKEN
    file_glob: true
    file: ./*.zip
    skip_cleanup: true
    on:
      branch: master
      python: "3.6"
      tags: true
  - provider: script
    script: submit-addon -r repo-scripts -b $BRANCH -s -m --pull-request $ADDON_ID
    on:
      branch: kodi-release
      python: "3.6"
notifications:
  email: false